version: "3.6"

x-service: &service
  restart: always

services:
  inkvisitor-database:
    <<: *service
    image: rethinkdb
    container_name: "inkvisitor-database"
    ports:
      - "8080:8080"
      - "28015:28015"
