FROM gplane/pnpm:8.6.0-node16-alpine as base

RUN apk add tzdata
ENV TZ=Europe/Prague
ENV CI=true

WORKDIR /app

ARG ENV

COPY ./packages .

WORKDIR /app/client
RUN pnpm install --frozen-lockfile

WORKDIR /app/server
RUN pnpm install --frozen-lockfile
