version: "3.6"

x-logging: &logging
  logging:
    options:
      max-size: "10m"
      max-file: "2"

services:
  database:
    image: rethinkdb
    container_name: "inkvisitor-database"
    restart: always
    <<: *logging
    volumes:
      - ./database_data:/data
    networks:
      - inkvisitor
    ports:
      - "8080:8080" # required only for public access
      - "28015:28015" # dashboard - required only for public access

  inkvisitor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: latest
    image: jancimertel/inkvisitor:latest
    container_name: inkvisitor
    restart: always
    <<: *logging
    env_file:
      - ./packages/server/env/.env
    environment:
      - DB_HOST=database
    ports:
      - "3000:3000"
    networks:
      - inkvisitor

networks:
  inkvisitor:
