export enum TerritoryType {
  Type1 = "1",
  Type2 = "2",
}

export namespace EntityEnums {
  // Helper function for testing if the class is part of PLOGESTRB group
  export const IsPLOGESTRB = (entityClass: Class): boolean => {
    return PLOGESTRB.indexOf(entityClass) !== -1;
  };

  // Helper function for testing if the class is part of PLOGESTR group
  export const IsPLOGESTR = (entityClass: Class): boolean => {
    return PLOGESTR.indexOf(entityClass) !== -1;
  };

  // Predicate for testing if input value is one of accepted class values
  export const IsClass = function (input: unknown, ...accepted: Class[]): boolean {
    return accepted.indexOf(input as Class) !== -1;
  };

  export enum Class {
    Action = "A",
    Territory = "T",
    Statement = "S",
    Resource = "R",
    Person = "P",
    Being = "B",
    Group = "G",
    Object = "O",
    Concept = "C",
    Location = "L",
    Value = "V",
    Event = "E",
  }

  export enum Extension {
    Any = "*",
    Empty = "empty",
    NoClass = "X",
    Invalid = "?",
  }

  export type ExtendedClass = Class | Extension;

  export const PLOGESTR = [
    Class.Person,
    Class.Location,
    Class.Object,
    Class.Group,
    Class.Event,
    Class.Statement,
    Class.Territory,
    Class.Resource,
  ];
  export const PLOGESTRB = [
    Class.Person,
    Class.Location,
    Class.Object,
    Class.Group,
    Class.Event,
    Class.Statement,
    Class.Territory,
    Class.Resource,
    Class.Being,
  ];
  export const PLOGESTRBV = [
    Class.Person,
    Class.Location,
    Class.Object,
    Class.Group,
    Class.Event,
    Class.Statement,
    Class.Territory,
    Class.Resource,
    Class.Being,
    Class.Value,
  ];
  export const ExtendedClasses = [
    Class.Action,
    Class.Territory,
    Class.Statement,
    Class.Resource,
    Class.Person,
    Class.Being,
    Class.Group,
    Class.Object,
    Class.Concept,
    Class.Location,
    Class.Value,
    Class.Event,
    Extension.Empty,
  ];

  /**
   * Helper function for testing if input value is valid extended class value
   * @param input
   * @returns
   */
  export const IsExtendedClass = (input: unknown): boolean => {
    return (
      Object.values(Class).indexOf(input as any) !== -1 ||
      Object.values(Extension).indexOf(input as any) !== -1
    );
  };

  export enum LogicalType {
    Definite = "1",
    Indefinite = "2",
    Hypothetical = "3",
    Generic = "4",
  }

  export enum Status {
    Pending = "0",
    Approved = "1",
    Discouraged = "2",
    Warning = "3",
    Unfinished = "4",
  }

  export enum Certainty {
    Empty = "0",
    Certain = "1",
    AlmostCertain = "2",
    Probable = "3",
    Possible = "4",
    Dubious = "5",
    False = "6",
  }

  export enum Elvl {
    Textual = "1",
    Interpretive = "2",
    Inferential = "3",
  }

  export enum Position {
    Subject = "s",
    Actant1 = "a1",
    Actant2 = "a2",
    PseudoActant = "pa",
  }

  export enum UsedInPosition {
    Value = "value",
    Type = "type",
    Actant = "actant",
    Action = "action",
    Tag = "tag",
  }

  export enum Logic {
    Positive = "1",
    Negative = "2",
  }

  export enum Mood {
    Indication = "1",
    Question = "2",
    Condition = "3",
    Possibility = "4",
    Probability = "5",
    Certitude = "6",
    Wish = "7",
    Order = "8",
    Licence = "9",
    Ability = "10",
    Belief = "11",
    Allegation = "12",
    Semblance = "13",
    Rectitude = "14",
    Expectation = "15",
    Exhortation = "16",
    Advice = "17",
  }

  export enum MoodVariant {
    Realis = "1",
    Irrealis = "2",
    ToBeDecided = "3",
  }

  export enum Virtuality {
    Reality = "1",
    Possibility = "2",
    Probability = "3",
    Certitude = "4",
    Allegation = "5",
    Semblance = "6",
  }

  export enum Partitivity {
    Unison = "1",
    UnisonOrParts = "2",
    UnisonOrDiscreteParts = "3",
    Parts = "4",
    DiscreteParts = "5",
  }

  export enum Operator {
    Xor = "x",
    And = "a",
    Or = "o",
    Greater = ">",
    GreaterOrEqual = ">=",
    Equal = "=",
    LessOrEqual = "<=",
    Less = "<",
  }
  // ISO 639-2 codes
  export enum Language {
    Empty = "",
    Chinese = "chi",
    Czech = "ces",
    Dutch = "dut",
    English = "eng",
    French = "fra",
    German = "deu",
    Hungarian = "hun",
    Italian = "ita",
    Japanese = "jpn",
    Latin = "lat",
    MiddleEnglish = "enm",
    MiddleFrench = "frm",
    MiddleHighGerman = "gmh",
    EarlyNewHighGerman = "enhg",
    Occitan = "oci",
    OldChurchSlavonic = "chu", // same as the Church Slavic
    OldEnglish = "ang",
    OldFrench = "fro",
    OldHighGerman = "goh",
    OldItalian = "ito", // not an ISO 639-2 code
    OldNorse = "non",
    OldOccitan = "pro",
    Polish = "pol",
    Portuguese = "por",
    Spanish = "spa",
    // Extensive ISO 639-2 code list (https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes)
    Afar = "aar",
    Abkhazian = "abk",
    Achinese = "ace",
    Acoli = "ach",
    Adangme = "ada",
    Adyghe = "ady",
    AfroAsiaticLanguages = "afa",
    Afrihili = "afh",
    Afrikaans = "afr",
    Ainu = "ain",
    Akan = "aka",
    Akkadian = "akk",
    Aleut = "ale",
    AlgonquianLanguages = "alg",
    SouthernAltai = "alt",
    Amharic = "amh",
    Angika = "anp",
    ApacheLanguages = "apa",
    Arabic = "ara",
    OfficialAramaicBCE = "arc",
    Aragonese = "arg",
    Mapudungun = "arn",
    Arapaho = "arp",
    ArtificialLanguages = "art",
    Arawak = "arw",
    Assamese = "asm",
    Asturian = "ast",
    AthapascanLanguages = "ath",
    AustralianLanguages = "aus",
    Avaric = "ava",
    Avestan = "ave",
    Awadhi = "awa",
    Aymara = "aym",
    Azerbaijani = "aze",
    BandaLanguages = "bad",
    BamilekeLanguages = "bai",
    Bashkir = "bak",
    Baluchi = "bal",
    Bambara = "bam",
    Balinese = "ban",
    Basa = "bas",
    BalticLanguages = "bat",
    Beja = "bej",
    Belarusian = "bel",
    Bemba = "bem",
    Bengali = "ben",
    BerberLanguages = "ber",
    Bhojpuri = "bho",
    BihariLanguages = "bih",
    Bikol = "bik",
    Bini = "bin",
    Bislama = "bis",
    Siksika = "bla",
    BantuLanguages = "bnt",
    Tibetan = "bod",
    Bosnian = "bos",
    Braj = "bra",
    Breton = "bre",
    BatakLanguages = "btk",
    Buriat = "bua",
    Buginese = "bug",
    Bulgarian = "bul",
    Blin = "byn",
    Caddo = "cad",
    CentralAmericanIndianLanguages = "cai",
    GalibiCarib = "car",
    Catalan = "cat",
    CaucasianLanguages = "cau",
    Cebuano = "ceb",
    CelticLanguages = "cel",
    Chamorro = "cha",
    Chibcha = "chb",
    Chechen = "che",
    Chagatai = "chg",
    Chuukese = "chk",
    Mari = "chm",
    ChinookJargon = "chn",
    Choctaw = "cho",
    Chipewyan = "chp",
    Cherokee = "chr",
    Chuvash = "chv",
    Cheyenne = "chy",
    ChamicLanguages = "cmc",
    Montenegrin = "cnr",
    Coptic = "cop",
    Cornish = "cor",
    Corsican = "cos",
    EnglishBasedCreolesAndPidgins = "cpe",
    FrenchBasedCreolesAndPidgins = "cpf",
    PortugueseBasedCreolesAndPidgins = "cpp",
    Cree = "cre",
    CrimeanTatar = "crh",
    CreolesAndPidgins = "crp",
    Kashubian = "csb",
    CushiticLanguages = "cus",
    Welsh = "cym",
    Dakota = "dak",
    Danish = "dan",
    Dargwa = "dar",
    LandDayakLanguages = "day",
    Delaware = "del",
    SlaveAthapascan = "den",
    Tlicho = "dgr",
    Dinka = "din",
    Divehi = "div",
    Dogri = "doi",
    DravidianLanguages = "dra",
    LowerSorbian = "dsb",
    Duala = "dua",
    MiddleDutch = "dum",
    Dyula = "dyu",
    Dzongkha = "dzo",
    Efik = "efi",
    EgyptianAncient = "egy",
    Ekajuk = "eka",
    ModernGreek = "ell",
    Elamite = "elx",
    Esperanto = "epo",
    Estonian = "est",
    Basque = "eus",
    Ewe = "ewe",
    Ewondo = "ewo",
    Fang = "fan",
    Faroese = "fao",
    Persian = "fas",
    Fanti = "fat",
    Fijian = "fij",
    Filipino = "fil",
    Finnish = "fin",
    FinnoUgrianLanguages = "fiu",
    Fon = "fon",
    NorthernFrisian = "frr",
    EasternFrisian = "frs",
    WesternFrisian = "fry",
    Fulah = "ful",
    Friulian = "fur",
    Ga = "gaa",
    Gayo = "gay",
    Gbaya = "gba",
    GermanicLanguages = "gem",
    Geez = "gez",
    Gilbertese = "gil",
    Gaelic = "gla",
    Irish = "gle",
    Galician = "glg",
    Manx = "glv",
    Gondi = "gon",
    Gorontalo = "gor",
    Gothic = "got",
    Grebo = "grb",
    AncientGreek = "grc",
    Guarani = "grn",
    SwissGerman = "gsw",
    Gujarati = "guj",
    Gwichin = "gwi",
    Haida = "hai",
    Haitian = "hat",
    Hausa = "hau",
    Hawaiian = "haw",
    Hebrew = "heb",
    Herero = "her",
    Hiligaynon = "hil",
    HimachaliLanguages = "him",
    Hindi = "hin",
    Hittite = "hit",
    Hmong = "hmn",
    HiriMotu = "hmo",
    Croatian = "hrv",
    UpperSorbian = "hsb",
    Hupa = "hup",
    Armenian = "hye",
    Iban = "iba",
    Igbo = "ibo",
    Ido = "ido",
    SichuanYi = "iii",
    IjoLanguages = "ijo",
    Inuktitut = "iku",
    Interlingue = "ile",
    Iloko = "ilo",
    InterlinguaInternationalAuxiliaryLanguageAssociation = "ina",
    IndicLanguages = "inc",
    Indonesian = "ind",
    IndoEuropeanLanguages = "ine",
    Ingush = "inh",
    Inupiaq = "ipk",
    IranianLanguages = "ira",
    IroquoianLanguages = "iro",
    Icelandic = "isl",
    Javanese = "jav",
    Lojban = "jbo",
    JudeoPersian = "jpr",
    JudeoArabic = "jrb",
    KaraKalpak = "kaa",
    Kabyle = "kab",
    Kachin = "kac",
    Kalaallisut = "kal",
    Kamba = "kam",
    Kannada = "kan",
    KarenLanguages = "kar",
    Kashmiri = "kas",
    Georgian = "kat",
    Kanuri = "kau",
    Kawi = "kaw",
    Kazakh = "kaz",
    Kabardian = "kbd",
    Khasi = "kha",
    KhoisanLanguages = "khi",
    CentralKhmer = "khm",
    Khotanese = "kho",
    Kikuyu = "kik",
    Kinyarwanda = "kin",
    Kirghiz = "kir",
    Kimbundu = "kmb",
    Konkani = "kok",
    Komi = "kom",
    Kongo = "kon",
    Korean = "kor",
    Kosraean = "kos",
    Kpelle = "kpe",
    KarachayBalkar = "krc",
    Karelian = "krl",
    KruLanguages = "kro",
    Kurukh = "kru",
    Kuanyama = "kua",
    Kumyk = "kum",
    Kurdish = "kur",
    Kutenai = "kut",
    Ladino = "lad",
    Lahnda = "lah",
    Lamba = "lam",
    Lao = "lao",
    Latvian = "lav",
    Lezghian = "lez",
    Limburgan = "lim",
    Lingala = "lin",
    Lithuanian = "lit",
    Mongo = "lol",
    Lozi = "loz",
    Luxembourgish = "ltz",
    LubaLulua = "lua",
    LubaKatanga = "lub",
    Ganda = "lug",
    Luiseno = "lui",
    Lunda = "lun",
    LuoKenyaAndTanzania = "luo",
    Lushai = "lus",
    Madurese = "mad",
    Magahi = "mag",
    Marshallese = "mah",
    Maithili = "mai",
    Makasar = "mak",
    Malayalam = "mal",
    Mandingo = "man",
    AustronesianLanguages = "map",
    Marathi = "mar",
    Masai = "mas",
    Moksha = "mdf",
    Mandar = "mdr",
    Mende = "men",
    MiddleIrish = "mga",
    Mikmaq = "mic",
    Minangkabau = "min",
    UncodedLanguages = "mis",
    Macedonian = "mkd",
    MonKhmerLanguages = "mkh",
    Malagasy = "mlg",
    Maltese = "mlt",
    Manchu = "mnc",
    Manipuri = "mni",
    ManoboLanguages = "mno",
    Mohawk = "moh",
    Mongolian = "mon",
    Mossi = "mos",
    Maori = "mri",
    Malay = "msa",
    MultipleLanguages = "mul",
    MundaLanguages = "mun",
    Creek = "mus",
    Mirandese = "mwl",
    Marwari = "mwr",
    Burmese = "mya",
    MayanLanguages = "myn",
    Erzya = "myv",
    NahuatlLanguages = "nah",
    NorthAmericanIndianLanguages = "nai",
    Neapolitan = "nap",
    Nauru = "nau",
    Navajo = "nav",
    SouthNdebele = "nbl",
    NorthNdebele = "nde",
    Ndonga = "ndo",
    LowGerman = "nds",
    Nepali = "nep",
    NepalBhasa = "new",
    Nias = "nia",
    NigerKordofanianLanguages = "nic",
    Niuean = "niu",
    NorwegianNynorsk = "nno",
    NorwegianBokmal = "nob",
    Nogai = "nog",
    Norwegian = "nor",
    NKo = "nqo",
    Pedi = "nso",
    NubianLanguages = "nub",
    ClassicalNewari = "nwc",
    Chichewa = "nya",
    Nyamwezi = "nym",
    Nyankole = "nyn",
    Nyoro = "nyo",
    Nzima = "nzi",
    Ojibwa = "oji",
    Oriya = "ori",
    Oromo = "orm",
    Osage = "osa",
    Ossetian = "oss",
    OttomanTurkish = "ota",
    OtomianLanguages = "oto",
    PapuanLanguages = "paa",
    Pangasinan = "pag",
    Pahlavi = "pal",
    Pampanga = "pam",
    Panjabi = "pan",
    Papiamento = "pap",
    Palauan = "pau",
    OldPersian = "peo",
    PhilippineLanguages = "phi",
    Phoenician = "phn",
    Pali = "pli",
    Pohnpeian = "pon",
    PrakritLanguages = "pra",
    Pushto = "pus",
    Quechua = "que",
    Rajasthani = "raj",
    Rapanui = "rap",
    Rarotongan = "rar",
    RomanceLanguages = "roa",
    Romansh = "roh",
    Romany = "rom",
    Romanian = "ron",
    Rundi = "run",
    Aromanian = "rup",
    Russian = "rus",
    Sandawe = "sad",
    Sango = "sag",
    Yakut = "sah",
    SouthAmericanIndianLanguages = "sai",
    SalishanLanguages = "sal",
    SamaritanAramaic = "sam",
    Sanskrit = "san",
    Sasak = "sas",
    Santali = "sat",
    Sicilian = "scn",
    Scots = "sco",
    Selkup = "sel",
    SemiticLanguages = "sem",
    OldIrish = "sga",
    SignLanguages = "sgn",
    Shan = "shn",
    Sidamo = "sid",
    Sinhala = "sin",
    SiouanLanguages = "sio",
    SinoTibetanLanguages = "sit",
    SlavicLanguages = "sla",
    Slovak = "slk",
    Slovenian = "slv",
    SouthernSami = "sma",
    NorthernSami = "sme",
    SamiLanguages = "smi",
    LuleSami = "smj",
    InariSami = "smn",
    Samoan = "smo",
    SkoltSami = "sms",
    Shona = "sna",
    Sindhi = "snd",
    Soninke = "snk",
    Sogdian = "sog",
    Somali = "som",
    SonghaiLanguages = "son",
    SouthernSotho = "sot",
    Albanian = "sqi",
    Sardinian = "srd",
    SrananTongo = "srn",
    Serbian = "srp",
    Serer = "srr",
    NiloSaharanLanguages = "ssa",
    Swati = "ssw",
    Sukuma = "suk",
    Sundanese = "sun",
    Susu = "sus",
    Sumerian = "sux",
    Swahili = "swa",
    Swedish = "swe",
    ClassicalSyriac = "syc",
    Syriac = "syr",
    Tahitian = "tah",
    TaiLanguages = "tai",
    Tamil = "tam",
    Tatar = "tat",
    Telugu = "tel",
    Timne = "tem",
    Tereno = "ter",
    Tetum = "tet",
    Tajik = "tgk",
    Tagalog = "tgl",
    Thai = "tha",
    Tigre = "tig",
    Tigrinya = "tir",
    Tiv = "tiv",
    Tokelau = "tkl",
    Klingon = "tlh",
    Tlingit = "tli",
    Tamashek = "tmh",
    TongaNyasa = "tog",
    TongaTongaIslands = "ton",
    TokPisin = "tpi",
    Tsimshian = "tsi",
    Tswana = "tsn",
    Tsonga = "tso",
    Turkmen = "tuk",
    Tumbuka = "tum",
    TupiLanguages = "tup",
    Turkish = "tur",
    AltaicLanguages = "tut",
    Tuvalu = "tvl",
    Twi = "twi",
    Tuvinian = "tyv",
    Udmurt = "udm",
    Ugaritic = "uga",
    Uighur = "uig",
    Ukrainian = "ukr",
    Umbundu = "umb",
    Undetermined = "und",
    Urdu = "urd",
    Uzbek = "uzb",
    Vai = "vai",
    Venda = "ven",
    Vietnamese = "vie",
    Volapk = "vol",
    Votic = "vot",
    WakashanLanguages = "wak",
    Wolaitta = "wal",
    Waray = "war",
    Washo = "was",
    SorbianLanguages = "wen",
    Walloon = "wln",
    Wolof = "wol",
    Kalmyk = "xal",
    Xhosa = "xho",
    Yao = "yao",
    Yapese = "yap",
    Yiddish = "yid",
    Yoruba = "yor",
    YupikLanguages = "ypk",
    Zapotec = "zap",
    Blissymbols = "zbl",
    Zenaga = "zen",
    StandardMoroccanTamazight = "zgh",
    Zhuang = "zha",
    ZandeLanguages = "znd",
    Zulu = "zul",
    Zuni = "zun",
    NoLinguisticContent = "zxx",
    Zaza = "zza",
  }

  export enum ResourceType {
    Type1 = "1",
    Type2 = "2",
  }

  export enum TerritoryType {
    Type1 = "1",
    Type2 = "2",
  }

  export enum Order {
    First = -9999,
    Last = 9999,
  }

  export enum ConceptPartOfSpeech {
    Empty = "",
    Noun = "noun",
    Adj = "adj",
    Pron = "pron",
    Adv = "adv",
    Num = "num",
    Adp = "adp",
    CConj = "cconj",
    SConj = "sconj",
    Det = "det",
    Intj = "intj",
    Part = "part",
  }
  export enum ActionPartOfSpeech {
    Verb = "verb",
  }
}
