export enum RelationType {
    Unknown = "",
    Superclass = "SC",
    SuperordinateLocation = "SOL",
    Synonym = "S",
    Antonym = "A",
    Troponym = "T",
    PropertyReciprocal = "PR",
    SubjectActantReciprocal = "SAR",
    ActionEventEquivalent = "AEE",
    Related = "RE",
    Classification = "C",
    Identification = "I",
    Holonymy = "H",
    Implication = "IM",
}
