name: deploy-1772-use-caching-in-ci

on:
  push:
    branches:
      - 1772-use-caching-in-ci

jobs: 
  client-dependencies:
    name: Build the client-dependencies docker stage
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: client-dependencies:latest
          target: client-dependencies
          outputs: type=docker,dest=client-dependencies.tar
        
      - name: Cache image.tar
        uses: actions/cache@v2
        with:
          path: client-dependencies.tar.gz
          key: client-dependencies-${{ github.sha }}.tar.gz
          
  staging-build:
    needs: [client-dependencies]
    name: Build the staging docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /tmp/client-dependencies.tar.gz
          key: client-dependencies-${{ github.sha }}.tar.gz
          
      - name: Load Docker image
        run: |
          docker load --input /tmp/client-dependencies.tar.gz
          docker image ls -a
          
      - name: Create env file for client
        run: |
          touch packages/client/env/.env.staging
          echo "$CLIENT_ENV" >> packages/client/env/.env.staging
        env:
          CLIENT_ENV: ${{secrets.CLIENT_ENV}}

      - name: Generate certificates
        run: |
          mkdir -p ./packages/server/secret
          openssl req -x509 -newkey rsa:2048 -nodes -out ./packages/server/secret/cert.pem -keyout ./packages/server/secret/key.pem -days 365 -subj "/C=FR/O=krkr/OU=Domain Control Validated/CN=*"
          
      - name: Run docker build task
        run: DOCKER_BUILDKIT=1 docker-compose build inkvisitor-staging

      - name: Save docker-compose stack
        run: docker save inkvisitor:staging | gzip > inkvisitor-staging.tar.gz

      - name: Cache image.tar
        uses: actions/cache@v2
        with:
          path: inkvisitor-staging.tar.gz
          key: inkvisitor-staging-${{ github.sha }}.tar.gz

  deploy:
    needs: [staging-build]
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout InkVisitor
        uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: inkvisitor-staging.tar.gz
          key: inkvisitor-staging-${{ github.sha }}.tar.gz

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Update packages
        run: |
          sudo apt-get update

      - name: Install OpenVPN
        run: |
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Prepare OpenVPN creds file
        run: |
          touch pass.txt
          echo ${{ secrets.VPN_USER }} >> pass.txt
          echo ${{ secrets.VPN_PASS }} >> pass.txt

      - name: Pull OpenVPN Config
        run: curl https://it.muni.cz/media/3404274/muni-main-linux.ovpn -o muni-linux.ovpn

      - name: Connect to VPN and deploy
        run: sudo openvpn --config muni-linux.ovpn --auth-user-pass pass.txt --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 2
        run: until ping -w 2 ${{ secrets.SSH_HOST }}; do sleep 2; done

      - name: Upload image staging
        run: scp inkvisitor-staging.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/apps
        
      - name: Load image
        run: |
          ssh -tt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}  -- "sh -c '
          podman container prune -f &&
          podman image prune -f &&
          rm -rf /var/tmp/docker-tar* &&
          podman rm inkvisitor-staging --force || true && 
          podman load -i /var/www/html/apps/inkvisitor-staging.tar.gz && 
          podman-compose -f /var/www/html/apps/docker-compose.yml up -d inkvisitor-staging
          '"

