name: dev
on:
  push:
    branches:
      - dev

jobs:
  build-staging:
    name: Build the staging docker image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create env file for client
        run: |
          touch packages/client/env/.env.staging
          echo "$CLIENT_ENV" >> packages/client/env/.env.staging
        env:
          CLIENT_ENV: ${{secrets.CLIENT_ENV}}

      - name: Run docker build task
        run: docker build -f Dockerfile --build-arg ENV=staging -t inkvisitor:staging .

  build-data-import:
    name: Build the data-import docker image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create env file for client
        run: |
          touch packages/client/env/.env.data-import
          echo "$CLIENT_ENV" >> packages/client/env/.env.data-import
        env:
          CLIENT_ENV: ${{secrets.CLIENT_ENV_DATAIMPORT}}

      - name: Run docker build task
        run: docker build -f Dockerfile --build-arg ENV=data-import -t inkvisitor:data-import .

  build-sandbox:
    name: Build the sandbox docker image
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create env file for client
        run: |
          touch packages/client/env/.env.sandbox
          echo "$CLIENT_ENV" >> packages/client/env/.env.sandbox
        env:
          CLIENT_ENV: ${{secrets.CLIENT_ENV_SANDBOX}}

      - name: Run docker build task
        run: docker build -f Dockerfile --build-arg ENV=sandbox -t inkvisitor:sandbox .
